#%RAML 1.0 NamedExample
value:
  -
    movieId: 1
    movieName: "Laxmi Bomb"
    movieDescription: "Horror Movie"
    Language: "Hindi"
    RunningLength: "144 minutes"
    ratings: "4"
    genre: "Horror"
  -
    movieId: 2
    movieName: "Thappad"
    movieDescription: "Drama Movie"
    Language: "Telugu"
    RunningLength: "150 minutes"
    ratings: "4"
    genre: "Drama"
  -
    movieId: 3
    movieName: "Malang"
    movieDescription: "Drama Movie"
    Language: "Hindi"
    RunningLength: "122 minutes"
    ratings: "3"
    genre: "Drama"
  -
    movieId: 4
    movieName: "Parasite"
    movieDescription: "Action Movie"
    Language: "English"
    RunningLength: "146 minutes"
    ratings: "5"
    genre: "Action"