#%RAML 1.0 NamedExample
value:
  -
    movieId: 1
    theatreId: 1
    theatreName: "escape cinemas"
    schedule: [2020-11-11T12:00:00, 2020-11-11T15:00:00, 2020-11-11T18:00:00]
    availableSeats: 4
    price: [250, 275, 300]